from features.services.OneSecmailService import OneSecmailService
import random


class PersonUtil(object):
    GENRE = ['Mr', 'Mrs'][random.randint(0, 1)]
    FIRST_NAME = ...
    LAST_NAME = ...
    EMAIL = OneSecmailService().generateNewEmail()
    PASSWORD = ...
    BITHDATE = ...
    ADDRESS = ...
    CITY = ...
    STATE = ...
    ZIP_POSTAL = ...
    COUNTRY = ...
    MOBILE_PHONE = ...
    SECOND_EMAIL = OneSecmailService().generateNewEmail()
